services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rss_feed_bot
      PGDATA: /var/lib/postgresql/data
    ports:
      - 9876:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
